package ai;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 * AgentReportParser — Reads the TestNG XML results file and converts it into
 * Java objects that CoverFoxTestAgent can reason about.
 *
 * Parses: test totals, per-test status, exception details, duration, stack trace.
 * Input : test-output/testng-results.xml  (auto-generated by TestNG after mvn test)
 */
public class AgentReportParser {

    // -----------------------------------------------------------------------
    // DATA MODELS
    // -----------------------------------------------------------------------

    /** One test method execution result */
    public static class TestResult {
        public final String testName;
        public final String className;
        public final String status;          // PASS | FAIL | SKIP
        public final String exceptionType;
        public final String exceptionMessage;
        public final String stackTrace;      // top portion of full stack trace
        public final long   durationMs;

        public TestResult(String testName, String className, String status,
                          String exceptionType, String exceptionMessage,
                          String stackTrace,   long durationMs) {
            this.testName         = testName;
            this.className        = className;
            this.status           = status;
            this.exceptionType    = exceptionType;
            this.exceptionMessage = exceptionMessage;
            this.stackTrace       = stackTrace;
            this.durationMs       = durationMs;
        }

        @Override
        public String toString() {
            return String.format("[%s] %s.%s (%dms)", status, className, testName, durationMs);
        }
    }

    /** Full suite-level summary */
    public static class SuiteReport {
        public int  total;
        public int  passed;
        public int  failed;
        public int  skipped;
        public final List<TestResult> allResults = new ArrayList<>();
        public final List<TestResult> failures   = new ArrayList<>();
        public final List<TestResult> slowTests  = new ArrayList<>(); // > 10 000 ms
    }

    // -----------------------------------------------------------------------
    // PARSER
    // -----------------------------------------------------------------------

    /**
     * Parses a TestNG testng-results.xml file into a SuiteReport.
     *
     * @param xmlPath  Absolute path to testng-results.xml
     * @throws RuntimeException if the file does not exist (run mvn test first)
     */
    public static SuiteReport parse(String xmlPath) throws Exception {
        File file = new File(xmlPath);
        if (!file.exists()) {
            throw new RuntimeException(
                "\n[Agent] TestNG results file not found at:\n  " + xmlPath +
                "\n[Agent] Please run 'mvn test' first, then re-run the agent.");
        }

        SuiteReport report = new SuiteReport();

        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        // Suppress external DTD loading (avoids network calls on some JDKs)
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        factory.setFeature("http://xml.org/sax/features/validation", false);
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.parse(file);
        doc.getDocumentElement().normalize();

        // Suite-level totals live on the root <testng-results> element
        Element root    = doc.getDocumentElement();
        report.total    = parseInt(root.getAttribute("total"));
        report.passed   = parseInt(root.getAttribute("passed"));
        report.failed   = parseInt(root.getAttribute("failed"));
        report.skipped  = parseInt(root.getAttribute("skipped"));

        // Walk all <test-method> elements
        NodeList methods = doc.getElementsByTagName("test-method");
        for (int i = 0; i < methods.getLength(); i++) {
            Element method = (Element) methods.item(i);

            // Skip @BeforeClass / @AfterClass / @BeforeMethod / @AfterMethod etc.
            if ("true".equals(method.getAttribute("is-config"))) {
                continue;
            }

            String name      = method.getAttribute("name");
            String status    = method.getAttribute("status");   // PASS | FAIL | SKIP
            long   duration  = parseLong(method.getAttribute("duration-ms"));
            String className = extractClassName(method.getAttribute("signature"));

            // Exception details (only present on failures)
            String exType  = "";
            String exMsg   = "";
            String exStack = "";
            NodeList exNodes = method.getElementsByTagName("exception");
            if (exNodes.getLength() > 0) {
                Element ex = (Element) exNodes.item(0);
                exType = ex.getAttribute("class");

                NodeList msgNodes = ex.getElementsByTagName("message");
                if (msgNodes.getLength() > 0) {
                    exMsg = msgNodes.item(0).getTextContent().trim();
                }

                // Grab first 10 lines of stack trace (enough context for AI)
                NodeList stackNodes = ex.getElementsByTagName("full-stacktrace");
                if (stackNodes.getLength() > 0) {
                    String fullStack = stackNodes.item(0).getTextContent().trim();
                    String[] lines   = fullStack.split("\n");
                    int      limit   = Math.min(lines.length, 10);
                    StringBuilder sb = new StringBuilder();
                    for (int j = 0; j < limit; j++) {
                        sb.append(lines[j].trim()).append("\n");
                    }
                    exStack = sb.toString();
                }
            }

            TestResult result = new TestResult(
                name, className, status, exType, exMsg, exStack, duration);

            report.allResults.add(result);
            if ("FAIL".equals(status))  report.failures.add(result);
            if (duration > 10_000)      report.slowTests.add(result);
        }

        return report;
    }

    // -----------------------------------------------------------------------
    // PRIVATE HELPERS
    // -----------------------------------------------------------------------

    /** Extracts the simple method name from a full TestNG signature string.
     *  e.g. "validateInsuranceCountForAge(java.lang.String)" → "validateInsuranceCountForAge" */
    private static String extractClassName(String signature) {
        if (signature == null || signature.isEmpty()) return "Unknown";
        String s = signature.contains("(")
            ? signature.substring(0, signature.indexOf("("))
            : signature;
        return s.contains(".")
            ? s.substring(s.lastIndexOf(".") + 1)
            : s;
    }

    private static int parseInt(String s) {
        try { return Integer.parseInt(s.trim()); } catch (Exception e) { return 0; }
    }

    private static long parseLong(String s) {
        try { return Long.parseLong(s.trim()); } catch (Exception e) { return 0L; }
    }
}
